In [1]:
import pandas as pd

data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv")

In [2]:
data

     fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
1      7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5
2     7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...
3     11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...
4      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5
...                                                 ...
1594  6.2;0.6;0.08;2;0.09;32;44;0.9949;3.45;0.58;10.5;5
1595  5.9;0.55;0.1;2.2;0.062;39;51;0.99512;3.52;0.76...
1596  6.3;0.51;0.13;2.3;0.076;29;40;0.99574;3.42;0.7...
1597  5.9;0.645;0.12;2;0.075;32;44;0.99547;3.57;0.71...
1598  6;0.31;0.47;3.6;0.067;18;42;0.99549;3.39;0.66;...

[1599 rows x 1 columns]

In [3]:
import pandas as pd

data=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

In [4]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [5]:
data.shape

(1599, 12)

In [6]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(data)

In [7]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1511,7.1,0.690,0.04,2.1,0.068,19.0,27.0,0.99712,3.44,0.67,9.8,5
952,8.2,0.310,0.40,2.2,0.058,6.0,10.0,0.99536,3.31,0.68,11.2,7
1250,7.1,0.600,0.01,2.3,0.079,24.0,37.0,0.99514,3.40,0.61,10.9,6
793,7.7,0.600,0.00,2.6,0.055,7.0,13.0,0.99639,3.38,0.56,10.8,5
123,8.0,0.710,0.00,2.6,0.080,11.0,34.0,0.99760,3.44,0.53,9.5,5
...,...,...,...,...,...,...,...,...,...,...,...,...
895,7.1,0.590,0.01,2.3,0.080,27.0,43.0,0.99550,3.42,0.58,10.7,6
877,7.7,0.715,0.01,2.1,0.064,31.0,43.0,0.99371,3.41,0.57,11.8,6
1228,5.1,0.420,0.00,1.8,0.044,18.0,88.0,0.99157,3.68,0.73,13.6,7
1187,7.0,0.430,0.30,2.0,0.085,6.0,39.0,0.99346,3.33,0.46,11.9,6
1543,11.1,0.440,0.42,2.2,0.064,14.0,19.0,0.99758,3.25,0.57,10.4,6

In [8]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
656,10.7,0.430,0.39,2.20,0.106,8.0,32.0,0.99860,2.89,0.50,9.60,5
1521,6.9,0.480,0.20,1.90,0.082,9.0,23.0,0.99585,3.39,0.43,9.05,4
840,11.1,0.420,0.47,2.65,0.085,9.0,34.0,0.99736,3.24,0.77,12.10,7
1505,6.7,0.760,0.02,1.80,0.078,6.0,12.0,0.99600,3.55,0.63,9.95,3
490,9.3,0.775,0.27,2.80,0.078,24.0,56.0,0.99840,3.31,0.67,10.60,6
...,...,...,...,...,...,...,...,...,...,...,...,...
279,8.9,0.400,0.32,5.60,0.087,10.0,47.0,0.99910,3.38,0.77,10.50,7
958,6.4,0.570,0.12,2.30,0.120,25.0,36.0,0.99519,3.47,0.71,11.30,7
635,8.7,0.840,0.00,1.40,0.065,24.0,33.0,0.99540,3.27,0.55,9.70,5
797,9.3,0.370,0.44,1.60,0.038,21.0,42.0,0.99526,3.24,0.81,10.80,7
403,11.4,0.600,0.49,2.70,0.085,10.0,41.0,0.99940,3.15,0.63,10.50,6

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import ElasticNet

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,accuracy_score,roc_auc_score
from sklearn.model_selection import  train_test_split

In [10]:
X_train=train.drop(["quality"],axis=1)
X_test=test.drop(["quality"],axis=1)
    
y_train=train[["quality"]]
y_test=test[["quality"]]

In [11]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)

C:\Users\Anjan\AppData\Local\Temp\ipykernel_436\4040854503.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)

RandomForestClassifier()

In [12]:
X_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
656,10.7,0.430,0.39,2.20,0.106,8.0,32.0,0.99860,2.89,0.50,9.60
1521,6.9,0.480,0.20,1.90,0.082,9.0,23.0,0.99585,3.39,0.43,9.05
840,11.1,0.420,0.47,2.65,0.085,9.0,34.0,0.99736,3.24,0.77,12.10
1505,6.7,0.760,0.02,1.80,0.078,6.0,12.0,0.99600,3.55,0.63,9.95
490,9.3,0.775,0.27,2.80,0.078,24.0,56.0,0.99840,3.31,0.67,10.60
...,...,...,...,...,...,...,...,...,...,...,...
279,8.9,0.400,0.32,5.60,0.087,10.0,47.0,0.99910,3.38,0.77,10.50
958,6.4,0.570,0.12,2.30,0.120,25.0,36.0,0.99519,3.47,0.71,11.30
635,8.7,0.840,0.00,1.40,0.065,24.0,33.0,0.99540,3.27,0.55,9.70
797,9.3,0.370,0.44,1.60,0.038,21.0,42.0,0.99526,3.24,0.81,10.80
403,11.4,0.600,0.49,2.70,0.085,10.0,41.0,0.99940,3.15,0.63,10.50

In [13]:
pred_prob=rf.predict_proba(X_test)

In [14]:
roc_auc_score=roc_auc_score(y_test,pred_prob,multi_class='ovr')

In [15]:
roc_auc_score

0.8190316348676592